In [1]:
import pandas as pd

In [3]:
elon_musk = pd.read_csv('ElonTweets(Sentiment) 10-28-22.csv')
elon_musk

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Datetime,Tweet Id,Text,Username,location,reply count,retweet count,like count,language,Twitter Access Point,Follower Count,Friends Count,verified,Date,mentions,sentiment
0,0,0,0,2022-10-28 03:49:11+00:00,1585841080431321088,the bird is freed,elonmusk,Twitter HQ,57663,128631,730472,en,Twitter for iPhone,110553384,122,True,2022-10-28,_,"['positive', 0.70848316]"
1,1,1,1,2022-10-28 01:50:49+00:00,1585811291851018241,Falcon rockets to orbit as seen from LA https:...,elonmusk,Twitter HQ,6857,16499,189436,en,Twitter for iPhone,110553384,122,True,2022-10-28,_,"['neutral', 0.90077394]"
2,2,2,2,2022-10-27 21:45:47+00:00,1585749627365515266,@Gfilche @Twitter ðŸ¤£,elonmusk,Twitter HQ,632,246,7052,und,Twitter for iPhone,110553384,122,True,2022-10-27,"Gfilche,Twitter","['neutral', 0.5714027]"
3,3,3,3,2022-10-27 16:17:39+00:00,1585667048020901888,@PeterSchiff ðŸ¤£ thanks,elonmusk,Twitter HQ,670,420,17577,en,Twitter for iPhone,110553384,122,True,2022-10-27,PeterSchiff,"['positive', 0.78971434]"
4,4,4,4,2022-10-27 13:19:25+00:00,1585622194696044544,@ZubyMusic Absolutely,elonmusk,Twitter HQ,1281,1152,42896,en,Twitter for iPhone,110553384,122,True,2022-10-27,ZubyMusic,"['neutral', 0.5287457]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17440,17440,17440,17440,2011-12-03 08:22:07+00:00,142881284019060736,That was a total non sequitur btw,elonmusk,Twitter HQ,27,9,51,en,Twitter for iPhone,110555351,122,True,2011-12-03,_,"['negative', 0.5067324]"
17441,17441,17441,17441,2011-12-03 08:20:28+00:00,142880871391838208,"Great Voltaire quote, arguably better than Twa...",elonmusk,Twitter HQ,23,29,53,en,Twitter for iPhone,110555351,122,True,2011-12-03,_,"['positive', 0.55860823]"
17442,17442,17442,17442,2011-12-01 10:29:04+00:00,142188458125963264,I made the volume on the Model S http://t.co/w...,elonmusk,Twitter HQ,29,13,75,en,Twitter Web Client,110555351,122,True,2011-12-01,_,"['neutral', 0.6384011]"
17443,17443,17443,17443,2011-12-01 09:55:11+00:00,142179928203460608,Went to Iceland on Sat to ride bumper cars on ...,elonmusk,Twitter HQ,33,22,188,en,Twitter Web Client,110555351,122,True,2011-12-01,_,"['positive', 0.9733198]"
17444,17444,17444,17444,2010-06-04 18:31:57+00:00,15434727182,"Please ignore prior tweets, as that was someon...",elonmusk,Twitter HQ,988,558,6023,en,Twitter Web Client,110555351,122,True,2010-06-04,_,"['neutral', 0.5472165]"