In [10]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns
import re
%matplotlib inline

In [3]:
elon_musk = pd.read_csv('ElonTweets(Sentiment) 10-28-22.csv')
elon_musk

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Datetime,Tweet Id,Text,Username,location,reply count,retweet count,like count,language,Twitter Access Point,Follower Count,Friends Count,verified,Date,mentions,sentiment
0,0,0,0,2022-10-28 03:49:11+00:00,1585841080431321088,the bird is freed,elonmusk,Twitter HQ,57663,128631,730472,en,Twitter for iPhone,110553384,122,True,2022-10-28,_,"['positive', 0.70848316]"
1,1,1,1,2022-10-28 01:50:49+00:00,1585811291851018241,Falcon rockets to orbit as seen from LA https:...,elonmusk,Twitter HQ,6857,16499,189436,en,Twitter for iPhone,110553384,122,True,2022-10-28,_,"['neutral', 0.90077394]"
2,2,2,2,2022-10-27 21:45:47+00:00,1585749627365515266,@Gfilche @Twitter ðŸ¤£,elonmusk,Twitter HQ,632,246,7052,und,Twitter for iPhone,110553384,122,True,2022-10-27,"Gfilche,Twitter","['neutral', 0.5714027]"
3,3,3,3,2022-10-27 16:17:39+00:00,1585667048020901888,@PeterSchiff ðŸ¤£ thanks,elonmusk,Twitter HQ,670,420,17577,en,Twitter for iPhone,110553384,122,True,2022-10-27,PeterSchiff,"['positive', 0.78971434]"
4,4,4,4,2022-10-27 13:19:25+00:00,1585622194696044544,@ZubyMusic Absolutely,elonmusk,Twitter HQ,1281,1152,42896,en,Twitter for iPhone,110553384,122,True,2022-10-27,ZubyMusic,"['neutral', 0.5287457]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17440,17440,17440,17440,2011-12-03 08:22:07+00:00,142881284019060736,That was a total non sequitur btw,elonmusk,Twitter HQ,27,9,51,en,Twitter for iPhone,110555351,122,True,2011-12-03,_,"['negative', 0.5067324]"
17441,17441,17441,17441,2011-12-03 08:20:28+00:00,142880871391838208,"Great Voltaire quote, arguably better than Twa...",elonmusk,Twitter HQ,23,29,53,en,Twitter for iPhone,110555351,122,True,2011-12-03,_,"['positive', 0.55860823]"
17442,17442,17442,17442,2011-12-01 10:29:04+00:00,142188458125963264,I made the volume on the Model S http://t.co/w...,elonmusk,Twitter HQ,29,13,75,en,Twitter Web Client,110555351,122,True,2011-12-01,_,"['neutral', 0.6384011]"
17443,17443,17443,17443,2011-12-01 09:55:11+00:00,142179928203460608,Went to Iceland on Sat to ride bumper cars on ...,elonmusk,Twitter HQ,33,22,188,en,Twitter Web Client,110555351,122,True,2011-12-01,_,"['positive', 0.9733198]"
17444,17444,17444,17444,2010-06-04 18:31:57+00:00,15434727182,"Please ignore prior tweets, as that was someon...",elonmusk,Twitter HQ,988,558,6023,en,Twitter Web Client,110555351,122,True,2010-06-04,_,"['neutral', 0.5472165]"

In [4]:
elon_musk['Date']= elon_musk['Datetime'].str.extract('(^\d*)')
elon_musk['Date'] = pd.to_datetime(elon_musk['Date'], format='%Y%m%d')
elon_musk

ValueError: time data '2022' does not match format '%Y%m%d' (match)

In [6]:
elon_musk['year'] = pd.DatetimeIndex(elon_musk['Datetime']).year

In [7]:
elon_musk

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Datetime,Tweet Id,Text,Username,location,reply count,retweet count,like count,language,Twitter Access Point,Follower Count,Friends Count,verified,Date,mentions,sentiment,year
0,0,0,0,2022-10-28 03:49:11+00:00,1585841080431321088,the bird is freed,elonmusk,Twitter HQ,57663,128631,730472,en,Twitter for iPhone,110553384,122,True,2022,_,"['positive', 0.70848316]",2022
1,1,1,1,2022-10-28 01:50:49+00:00,1585811291851018241,Falcon rockets to orbit as seen from LA https:...,elonmusk,Twitter HQ,6857,16499,189436,en,Twitter for iPhone,110553384,122,True,2022,_,"['neutral', 0.90077394]",2022
2,2,2,2,2022-10-27 21:45:47+00:00,1585749627365515266,@Gfilche @Twitter ðŸ¤£,elonmusk,Twitter HQ,632,246,7052,und,Twitter for iPhone,110553384,122,True,2022,"Gfilche,Twitter","['neutral', 0.5714027]",2022
3,3,3,3,2022-10-27 16:17:39+00:00,1585667048020901888,@PeterSchiff ðŸ¤£ thanks,elonmusk,Twitter HQ,670,420,17577,en,Twitter for iPhone,110553384,122,True,2022,PeterSchiff,"['positive', 0.78971434]",2022
4,4,4,4,2022-10-27 13:19:25+00:00,1585622194696044544,@ZubyMusic Absolutely,elonmusk,Twitter HQ,1281,1152,42896,en,Twitter for iPhone,110553384,122,True,2022,ZubyMusic,"['neutral', 0.5287457]",2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17440,17440,17440,17440,2011-12-03 08:22:07+00:00,142881284019060736,That was a total non sequitur btw,elonmusk,Twitter HQ,27,9,51,en,Twitter for iPhone,110555351,122,True,2011,_,"['negative', 0.5067324]",2011
17441,17441,17441,17441,2011-12-03 08:20:28+00:00,142880871391838208,"Great Voltaire quote, arguably better than Twa...",elonmusk,Twitter HQ,23,29,53,en,Twitter for iPhone,110555351,122,True,2011,_,"['positive', 0.55860823]",2011
17442,17442,17442,17442,2011-12-01 10:29:04+00:00,142188458125963264,I made the volume on the Model S http://t.co/w...,elonmusk,Twitter HQ,29,13,75,en,Twitter Web Client,110555351,122,True,2011,_,"['neutral', 0.6384011]",2011
17443,17443,17443,17443,2011-12-01 09:55:11+00:00,142179928203460608,Went to Iceland on Sat to ride bumper cars on ...,elonmusk,Twitter HQ,33,22,188,en,Twitter Web Client,110555351,122,True,2011,_,"['positive', 0.9733198]",2011
17444,17444,17444,17444,2010-06-04 18:31:57+00:00,15434727182,"Please ignore prior tweets, as that was someon...",elonmusk,Twitter HQ,988,558,6023,en,Twitter Web Client,110555351,122,True,2010,_,"['neutral', 0.5472165]",2010

In [8]:
elon_musk_2021 = elon_musk[elon_musk['year'] == 2021]

In [9]:
elon_musk_2021

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Datetime,Tweet Id,Text,Username,location,reply count,retweet count,like count,language,Twitter Access Point,Follower Count,Friends Count,verified,Date,mentions,sentiment,year
3135,3135,3135,3135,2021-12-31 02:23:58+00:00,1476740887543791617,@TheBabylonBee ðŸ¤£,elonmusk,Twitter HQ,987,687,21062,und,Twitter for iPhone,110553725,122,True,2021,TheBabylonBee,"['neutral', 0.52986854]",2021
3136,3136,3136,3136,2021-12-30 21:11:23+00:00,1476662222617251846,@roshanpateI ðŸ¤£ $7,elonmusk,Twitter HQ,756,340,12985,und,Twitter for iPhone,110553725,122,True,2021,roshanpateI,"['neutral', 0.69755554]",2021
3137,3137,3137,3137,2021-12-30 20:47:53+00:00,1476656306610216960,@tesla_raj Many UI improvements coming,elonmusk,Twitter HQ,972,418,11841,ca,Twitter for iPhone,110553725,122,True,2021,tesla_raj,"['positive', 0.797664]",2021
3138,3138,3138,3138,2021-12-30 20:28:51+00:00,1476651519986614281,@CSmithson80 @heydave7 @BLKMDL3 @mims This cha...,elonmusk,Twitter HQ,238,136,2450,en,Twitter for iPhone,110553725,122,True,2021,"CSmithson80,heydave7,BLKMDL3,mims","['positive', 0.79169226]",2021
3139,3139,3139,3139,2021-12-30 18:23:14+00:00,1476619907076923398,@BLKMDL3 @mims Predicting macroeconomics is ch...,elonmusk,Twitter HQ,730,1605,6610,en,Twitter for iPhone,110553725,122,True,2021,"BLKMDL3,mims","['neutral', 0.54506123]",2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,6132,6132,6132,2021-01-02 14:59:09+00:00,1345384139969552389,@flcnhvy Tesla is responsible for 2/3 of all t...,elonmusk,Twitter HQ,618,643,12589,en,Twitter for iPhone,110554098,122,True,2021,flcnhvy,"['neutral', 0.43212065]",2021
6133,6133,6133,6133,2021-01-02 14:51:49+00:00,1345382294966571008,So proud of the Tesla team for achieving this ...,elonmusk,Twitter HQ,3944,5820,104724,en,Twitter for iPhone,110554098,122,True,2021,_,"['positive', 0.98368937]",2021
6134,6134,6134,6134,2021-01-02 12:23:28+00:00,1345344958710992897,"@newscientist Um, we have giant fusion reactor...",elonmusk,Twitter HQ,1811,2210,50314,en,Twitter for iPhone,110554098,122,True,2021,newscientist,"['positive', 0.59646]",2021
6135,6135,6135,6135,2021-01-02 03:20:48+00:00,1345208391958888448,@comma_ai Tesla Full Self-Driving will work at...,elonmusk,Twitter HQ,635,869,19773,en,Twitter for iPhone,110554098,122,True,2021,comma_ai,"['positive', 0.81392205]",2021
6136,6136,6136,6136,2021-01-01 00:58:30+00:00,1344810193952014336,"@PPathole Dojo isnâ€™t needed, but will make sel...",elonmusk,Twitter HQ,213,207,3461,en,Twitter for iPhone,110554098,122,True,2021,PPathole,"['neutral', 0.479866]",2021

In [12]:
elon_musk_2021.shape

(3002, 20)

In [17]:
musk_tweets_2021 = pd.DataFrame(elon_musk_2021['Text'])

In [18]:
musk_tweets_2021

                                                   Text
3135                                   @TheBabylonBee ðŸ¤£
3136                                  @roshanpateI ðŸ¤£ $7
3137             @tesla_raj Many UI improvements coming
3138  @CSmithson80 @heydave7 @BLKMDL3 @mims This cha...
3139  @BLKMDL3 @mims Predicting macroeconomics is ch...
...                                                 ...
6132  @flcnhvy Tesla is responsible for 2/3 of all t...
6133  So proud of the Tesla team for achieving this ...
6134  @newscientist Um, we have giant fusion reactor...
6135  @comma_ai Tesla Full Self-Driving will work at...
6136  @PPathole Dojo isnâ€™t needed, but will make sel...

[3002 rows x 1 columns]